export { Header } from './Header/Header';
export { Register } from './form/register/Register';
export { RequireAuth } from './auth/RequireAuth';
export { layout } from './layout/Layout';
export { DashBoard } from './dashboard/DashBoard';
export { Issue } from './Issue/Issues';
export { User } from './User/User';
export { Login } from './form/login/Login';
export { Sidebar } from './Sidebar/Sidebar';
export { Book } from './Book/Book';
// export { SearchBar } from './../components/Search/SearchBar';
